# Licensed under the Apache License. See footer for details.

require "../../lib/cakex"

log "running test: #{path.basename path.dirname __filename}"

process.on "uncaughtException", (e) ->
  log "uncaughtException: #{e}"
  log e.stack

waitLength = null
#-------------------------------------------------------------------------------
task "test", "run test", ->

  waitLength = 2000

  spawnWaiter()
  setTimeout spawnWaiter, 1000
  setTimeout spawnWaiter, 2000
  setTimeout spawnWaiter, 3000
  setTimeout spawnWaiter, 4000

  setTimeout (-> waitLength = 500), 8000
  setTimeout spawnWaiter, 10000
  setTimeout spawnWaiter, 11000
  setTimeout spawnWaiter, 12000
  setTimeout spawnWaiter, 13000


#-------------------------------------------------------------------------------
count = 0
spawnWaiter = ->
  count++
  daemon.start "waiter", "node", ["waiter", count, waitLength]

#-------------------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
