// Generated by CoffeeScript 1.9.0
var Daemons, child_process, daemon, killAll;

child_process = require("child_process");

daemon = exports;

Daemons = {};

process.on("uncaughtException", function(err) {
  log("uncaughtException: " + err);
  return log(err.stack);
});

process.on("exit", function() {
  return killAll();
});

process.on("SIGTERM", function() {
  return killAll();
});

process.on("SIGINT", function() {
  return killAll();
});

process.on("SIGBREAK", function() {
  return killAll();
});

process.on("uncaughtException", function() {
  return killAll();
});

daemon.start = function(handle, program, args, options) {
  if (options == null) {
    options = {};
  }
  daemon.kill(handle, function() {
    var serverProcess;
    if (options.stdio == null) {
      options.stdio = "inherit";
    }
    serverProcess = child_process.spawn(program, args, options);
    Daemons[handle] = serverProcess;
    return serverProcess.on("exit", function() {
      return delete Daemons[handle];
    });
  });
};

daemon.kill = function(handle, cb) {
  var serverProcess;
  serverProcess = Daemons[handle];
  if (serverProcess == null) {
    if (cb != null) {
      cb();
    }
    return;
  }
  delete Daemons[handle];
  serverProcess.on("exit", function() {
    if (cb != null) {
      return cb();
    }
  });
  serverProcess.kill();
};

killAll = function() {
  var handle, serverProcess;
  for (handle in Daemons) {
    serverProcess = Daemons[handle];
    serverProcess.kill();
  }
  return exit();
};

//# sourceMappingURL=daemon.js.map
